services:
  glpi:
    image: ${IMAGE}
    container_name: ${CONTAINER_NAME}
    environment:
      DB_SERVER_HOST: ${GLPI_DB_HOST}
      MYSQL_DATABASE: ${GLPI_DB_NAME}
      MYSQL_USER: ${GLPI_DB_USER}
      MYSQL_PASSWORD: ${GLPI_DB_PASSWORD}
      PHP_TZ: ${PHP_TZ}
    ports:
      - ${PORTS}
    volumes:
      - ${VOL_GLPI}
      - ${VOL_CRON}
      #- ${VOL_TIMEZONE}
      - ${VOL_LOCALTIME}
    networks:
      network-share:
        ipv4_address: ${IPV4_GLPI}
    restart: unless-stopped

networks:
  network-share:
    external: true
    ipam:
      config:
        - subnet: ${SUBNET}
