services:
  glpi:
    image: ${IMAGE}
    container_name: ${CONTAINER_NAME}
    environment:
      GLPI_DB_HOST: ${GLPI_DB_HOST}
      GLPI_DB_PORT: 3306
      GLPI_DB_NAME: ${GLPI_DB_NAME}
      GLPI_DB_USER: ${GLPI_DB_USER}
      GLPI_DB_PASSWORD: ${GLPI_DB_PASSWORD}
      GLPI_AUTO_INSTALL: "true"
      PHP_TZ: ${PHP_TZ}
    ports:
      - ${PORTS}
    volumes:
      - ${VOL_GLPI}
      - ${VOL_CRON}
      - ${VOL_TIMEZONE}
      - ${VOL_LOCALTIME}
    networks:
      network-share:
        ipv4_address: ${IPV4_GLPI}
    restart: unless-stopped

networks:
  network-share:
    external: true
    ipam:
      config:
        - subnet: ${SUBNET}
